export interface RaceType {
  id: number;
  code: string;
  name: string;
  disciplineId: number;
  isPara: boolean;
  isActive: boolean;
}

export interface RaceTypeOption {
  label: string;
  value: string | null;
}

export const raceTypes: RaceType[] = [
  { id: 1, code: "4X", name: "4X", disciplineId: 7, isPara: false, isActive: true },
  { id: 2, code: "6D", name: "Six-Day Race", disciplineId: 9, isPara: false, isActive: false },
  { id: 3, code: "AFR", name: "Africa Tour", disciplineId: 10, isPara: false, isActive: false },
  { id: 4, code: "ALL", name: "All divisions", disciplineId: 8, isPara: true, isActive: true },
  { id: 5, code: "AME", name: "America Tour", disciplineId: 10, isPara: false, isActive: false },
  { id: 6, code: "ASI", name: "Asia Tour", disciplineId: 10, isPara: false, isActive: false },
  { id: 7, code: "BVI", name: "Visually Impaired", disciplineId: 8, isPara: true, isActive: true },
  { id: 8, code: "PIS-C1", name: "Points Race Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 9, code: "CBL", name: "Cycle-ball", disciplineId: 5, isPara: false, isActive: true },
  { id: 10, code: "CM", name: "Cycling For All Mountain Bike", disciplineId: 7, isPara: false, isActive: false },
  { id: 11, code: "CP", name: "Cerebral Palsy", disciplineId: 8, isPara: true, isActive: true },
  { id: 12, code: "CP1", name: "Cerebral Palsy 1", disciplineId: 8, isPara: true, isActive: true },
  { id: 13, code: "CP2", name: "Cerebral Palsy 2", disciplineId: 8, isPara: true, isActive: true },
  { id: 14, code: "CP3", name: "Cerebral Palsy 3", disciplineId: 8, isPara: true, isActive: true },
  { id: 15, code: "CP4", name: "Cerebral Palsy 4", disciplineId: 8, isPara: true, isActive: true },
  { id: 16, code: "CR", name: "Cycling For All Road", disciplineId: 10, isPara: false, isActive: false },
  { id: 17, code: "DD", name: "DH - Divers", disciplineId: 7, isPara: false, isActive: false },
  { id: 18, code: "DH", name: "Downhill", disciplineId: 7, isPara: false, isActive: false },
  { id: 19, code: "DHI", name: "Downhill", disciplineId: 7, isPara: false, isActive: true },
  { id: 20, code: "DHM", name: "Mass Downhill", disciplineId: 7, isPara: false, isActive: true },
  { id: 21, code: "DL", name: "DH - Dual", disciplineId: 7, isPara: false, isActive: false },
  { id: 22, code: "DS", name: "Dual Slalom", disciplineId: 7, isPara: false, isActive: false },
  { id: 23, code: "ED", name: "Pacing Ranking", disciplineId: 9, isPara: false, isActive: true },
  { id: 24, code: "EL", name: "Elimination Race", disciplineId: 9, isPara: false, isActive: true },
  { id: 25, code: "EN", name: "Cross Country Enduro Racing", disciplineId: 7, isPara: false, isActive: false },
  { id: 26, code: "EUR", name: "Europe Tour", disciplineId: 10, isPara: false, isActive: false },
  { id: 27, code: "FAW", name: "Four Artistic Cycling Women", disciplineId: 5, isPara: false, isActive: false },
  { id: 28, code: "HC", name: "Handcycling", disciplineId: 8, isPara: true, isActive: true },
  { id: 29, code: "HCA", name: "Handcycling A", disciplineId: 8, isPara: true, isActive: true },
  { id: 30, code: "HCB", name: "Handcycling B", disciplineId: 8, isPara: true, isActive: true },
  { id: 31, code: "HCC", name: "Handcycling C", disciplineId: 8, isPara: true, isActive: true },
  { id: 32, code: "HC-X", name: "Hill Climb", disciplineId: 7, isPara: false, isActive: false },
  { id: 33, code: "HCY", name: "Handcycling", disciplineId: 8, isPara: true, isActive: true },
  { id: 34, code: "IL", name: "In Line", disciplineId: 11, isPara: false, isActive: false },
  { id: 35, code: "IP", name: "Individual Pursuit", disciplineId: 9, isPara: false, isActive: true },
  { id: 36, code: "IRR", name: "Individual Road Race", disciplineId: 10, isPara: false, isActive: true },
  { id: 37, code: "ITT", name: "Individual Time Trial", disciplineId: 10, isPara: false, isActive: true },
  { id: 38, code: "K1", name: "1km 500m Time Trial Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 39, code: "KE", name: "Keirin", disciplineId: 9, isPara: false, isActive: true },
  { id: 40, code: "KF", name: "500 m Time Trial", disciplineId: 9, isPara: false, isActive: false },
  { id: 41, code: "KT", name: "Time Trial", disciplineId: 9, isPara: false, isActive: true },
  { id: 42, code: "LC", name: "Amputees", disciplineId: 8, isPara: true, isActive: true },
  { id: 43, code: "LC1", name: "Amputees 1", disciplineId: 8, isPara: true, isActive: true },
  { id: 44, code: "LC2", name: "Amputees 2", disciplineId: 8, isPara: true, isActive: true },
  { id: 45, code: "LC3", name: "Amputees 3", disciplineId: 8, isPara: true, isActive: true },
  { id: 46, code: "LC4", name: "Amputees 4", disciplineId: 8, isPara: true, isActive: true },
  { id: 47, code: "M1", name: "Madison Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 48, code: "MA", name: "Madison", disciplineId: 9, isPara: false, isActive: true },
  { id: 49, code: "MD", name: "DH - Masse Downhill", disciplineId: 7, isPara: false, isActive: false },
  { id: 50, code: "MX", name: "XC - Marathon", disciplineId: 7, isPara: false, isActive: false },
  { id: 51, code: "N1", name: "Keirin Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 52, code: "NO", name: "Nations Open", disciplineId: 11, isPara: false, isActive: false },
  { id: 53, code: "NR", name: "No RaceType", disciplineId: 11, isPara: false, isActive: false },
  { id: 54, code: "OCE", name: "Oceania Tour", disciplineId: 10, isPara: false, isActive: false },
  { id: 55, code: "OS", name: "Olympic Sprint", disciplineId: 9, isPara: false, isActive: true },
  { id: 56, code: "OT", name: "Mountain Bike Trials", disciplineId: 11, isPara: false, isActive: false },
  { id: 57, code: "OX", name: "XC - Olympique Format", disciplineId: 7, isPara: false, isActive: false },
  { id: 58, code: "P1", name: "Individual Pursuit Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 59, code: "PAM", name: "Pair Artistic Cycling Men", disciplineId: 5, isPara: false, isActive: true },
  { id: 60, code: "PAW", name: "Pair Artistic Cycling Women", disciplineId: 5, isPara: false, isActive: true },
  { id: 61, code: "PIS", name: "Track Race", disciplineId: 8, isPara: false, isActive: true },
  { id: 62, code: "PIS-IP", name: "Individual Pursuit", disciplineId: 8, isPara: false, isActive: true },
  { id: 63, code: "PIS-KF", name: "500 m Time Trial", disciplineId: 8, isPara: false, isActive: true },
  { id: 64, code: "PIS-KT", name: "1 km Time Trial", disciplineId: 8, isPara: false, isActive: true },
  { id: 65, code: "PIS-SP", name: "Sprint", disciplineId: 8, isPara: false, isActive: true },
  { id: 66, code: "PIS-TS", name: "Team Sprint", disciplineId: 8, isPara: false, isActive: true },
  { id: 67, code: "PMI", name: "Pair Artistic Cycling Mix", disciplineId: 5, isPara: false, isActive: true },
  { id: 68, code: "PP", name: "XC - Cross Country Point to Point", disciplineId: 7, isPara: false, isActive: false },
  { id: 69, code: "PR", name: "Points Race", disciplineId: 9, isPara: false, isActive: true },
  { id: 70, code: "R1", name: "Scratch Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 71, code: "ROA", name: "Road Race", disciplineId: 8, isPara: false, isActive: true },
  { id: 72, code: "ROA-IRR", name: "Individual Road Race", disciplineId: 8, isPara: false, isActive: true },
  { id: 73, code: "ROA-ITT", name: "Individual Time Trial", disciplineId: 8, isPara: false, isActive: true },
  { id: 74, code: "S1", name: "Team Sprint Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 75, code: "SAM", name: "Single Artistic Cycling Men", disciplineId: 5, isPara: false, isActive: true },
  { id: 76, code: "SAW", name: "Single Artistic Cycling Women", disciplineId: 5, isPara: false, isActive: true },
  { id: 77, code: "SC", name: "XC - Cross Country Short circuit", disciplineId: 7, isPara: false, isActive: false },
  { id: 78, code: "SH", name: "Scratch", disciplineId: 9, isPara: false, isActive: true },
  { id: 79, code: "SP", name: "Sprint", disciplineId: 9, isPara: false, isActive: true },
  { id: 80, code: "SR", name: "XC - Stage Race", disciplineId: 7, isPara: false, isActive: false },
  { id: 81, code: "ST", name: "Sprint Ranking", disciplineId: 9, isPara: false, isActive: true },
  { id: 82, code: "PIS-T1", name: "Team Pursuit Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 83, code: "TP", name: "Team Pursuit", disciplineId: 9, isPara: false, isActive: true },
  { id: 84, code: "TR", name: "XC - Team Relay", disciplineId: 7, isPara: true, isActive: false },
  { id: 85, code: "TS", name: "Team Sprint", disciplineId: 9, isPara: false, isActive: true },
  { id: 86, code: "TT", name: "XC - Time Trial", disciplineId: 7, isPara: false, isActive: false },
  { id: 87, code: "TTT", name: "Team Time Trial", disciplineId: 10, isPara: false, isActive: true },
  { id: 88, code: "V1", name: "Sprint Juniors", disciplineId: 9, isPara: false, isActive: false },
  { id: 89, code: "XC", name: "Cross-country", disciplineId: 7, isPara: false, isActive: false },
  { id: 90, code: "XCC", name: "Cross-country short circuit", disciplineId: 7, isPara: false, isActive: true },
  { id: 91, code: "XCM", name: "Cross-country marathon", disciplineId: 7, isPara: false, isActive: true },
  { id: 92, code: "XCO", name: "Cross-country Olympic", disciplineId: 7, isPara: false, isActive: true },
  { id: 93, code: "XCP", name: "Cross-country point-to-point", disciplineId: 7, isPara: false, isActive: true },
  { id: 94, code: "XCR", name: "Cross-country team relay", disciplineId: 7, isPara: false, isActive: true },
  { id: 95, code: "XCT", name: "Cross-country time trial", disciplineId: 7, isPara: false, isActive: true },
  { id: 96, code: "XD", name: "XC - Divers", disciplineId: 7, isPara: false, isActive: false },
  { id: 97, code: "B", name: "Tandem", disciplineId: 8, isPara: true, isActive: true },
  { id: 98, code: "C", name: "Cycle", disciplineId: 8, isPara: true, isActive: true },
  { id: 99, code: "C1", name: "Cycle 1", disciplineId: 8, isPara: true, isActive: true },
  { id: 100, code: "C2", name: "Cycle 2", disciplineId: 8, isPara: true, isActive: true },
  { id: 101, code: "C3", name: "Cycle 3", disciplineId: 8, isPara: true, isActive: true },
  { id: 102, code: "C4", name: "Cycle 4", disciplineId: 8, isPara: true, isActive: true },
  { id: 103, code: "C5", name: "Cycle 5", disciplineId: 8, isPara: true, isActive: true },
  { id: 104, code: "T1", name: "Tricycle 1", disciplineId: 8, isPara: true, isActive: true },
  { id: 105, code: "T2", name: "Tricycle 2", disciplineId: 8, isPara: true, isActive: true },
  { id: 106, code: "H", name: "Handbike", disciplineId: 8, isPara: true, isActive: true },
  { id: 107, code: "H1", name: "Handbike 1", disciplineId: 8, isPara: true, isActive: true },
  { id: 108, code: "H2", name: "Handbike 2", disciplineId: 8, isPara: true, isActive: true },
  { id: 109, code: "H3", name: "Handbike 3", disciplineId: 8, isPara: true, isActive: true },
  { id: 110, code: "H4", name: "Handbike 4", disciplineId: 8, isPara: true, isActive: true },
  { id: 111, code: "T", name: "Tricycle", disciplineId: 8, isPara: true, isActive: true },
  { id: 112, code: "XCE", name: "Cross-country eliminator", disciplineId: 7, isPara: false, isActive: true },
  { id: 116, code: "XCS", name: "Cross-country stage races", disciplineId: 7, isPara: false, isActive: true },
  { id: 118, code: "OM", name: "Omnium", disciplineId: 9, isPara: false, isActive: true },
  { id: 119, code: "PIS-SH", name: "Scratch", disciplineId: 8, isPara: false, isActive: true },
  { id: 120, code: "H5", name: "Handbike 5", disciplineId: 8, isPara: true, isActive: true },
  { id: 121, code: "ROA-TR", name: "Team Relay", disciplineId: 8, isPara: false, isActive: true },
  { id: 122, code: "END", name: "Enduro", disciplineId: 7, isPara: false, isActive: true },
  { id: 123, code: "PAR", name: "Para-Cycling", disciplineId: 9, isPara: false, isActive: true },
  { id: 125, code: "ACT4", name: "Artistic Cycling ACT4", disciplineId: 5, isPara: false, isActive: true },
  { id: 126, code: "20''", name: "20-inch Wheel Size", disciplineId: 12, isPara: false, isActive: true },
  { id: 127, code: "26''", name: "26-inch Wheel Size", disciplineId: 12, isPara: false, isActive: true },
  { id: 128, code: "BMX-IND", name: "Individual", disciplineId: 1, isPara: false, isActive: true },
  { id: 129, code: "CRO-IND", name: "Individual", disciplineId: 3, isPara: false, isActive: true },
  { id: 130, code: "OPN", name: "Open", disciplineId: 12, isPara: false, isActive: true },
  { id: 131, code: "ROA-CC", name: "Combined Classification", disciplineId: 8, isPara: false, isActive: true },
  { id: 132, code: "XCO-JS", name: "Cross-country Olympic Junior Series", disciplineId: 7, isPara: false, isActive: true },
  { id: 133, code: "XCM-MS", name: "Cross-country marathon Series", disciplineId: 7, isPara: false, isActive: true },
  { id: 134, code: "BMX-TT", name: "Time Trial", disciplineId: 1, isPara: false, isActive: true },
  { id: 135, code: "BFR-IND", name: "Individual", disciplineId: 13, isPara: false, isActive: true },
  { id: 136, code: "BFR-FLT", name: "Flatland", disciplineId: 13, isPara: false, isActive: true },
  { id: 137, code: "BFR-PRK", name: "Park", disciplineId: 13, isPara: false, isActive: true },
  { id: 138, code: "MP", name: "Motor-Pacing", disciplineId: 9, isPara: false, isActive: true },
  { id: 139, code: "E-XC", name: "E-MTB Cross-country", disciplineId: 7, isPara: false, isActive: true },
  { id: 140, code: "E-END", name: "E-MTB Enduro", disciplineId: 7, isPara: false, isActive: true },
  { id: 141, code: "TTM", name: "Team time trial mixed relay", disciplineId: 10, isPara: false, isActive: true },
  { id: 142, code: "PUM", name: "Pump Track", disciplineId: 7, isPara: false, isActive: true },
  { id: 143, code: "PIS-OM", name: "Omnium", disciplineId: 8, isPara: false, isActive: true },
  { id: 144, code: "PIS-TTS", name: "Mixed Tandem Team Sprint", disciplineId: 8, isPara: false, isActive: true },
  { id: 147, code: "TO", name: "Tempo Race", disciplineId: 9, isPara: false, isActive: true },
  { id: 148, code: "SNO", name: "Snow Bike", disciplineId: 7, isPara: false, isActive: true },
  { id: 149, code: "E-XCM", name: "E-MTB Cross-Country Marathon", disciplineId: 7, isPara: false, isActive: true },
  { id: 154, code: "CRO-TR", name: "Team Relay", disciplineId: 3, isPara: false, isActive: true },
  { id: 155, code: "GRA-IND", name: "Individual", disciplineId: 15, isPara: false, isActive: true },
  { id: 156, code: "EDR", name: "Enduro", disciplineId: 7, isPara: false, isActive: true },
  { id: 157, code: "EDR-E", name: "Enduro Electric", disciplineId: 7, isPara: false, isActive: true },
  { id: 159, code: "MIT", name: "Mixed Team", disciplineId: 12, isPara: false, isActive: true },
  { id: 161, code: "SNO-DS", name: "Snow Bike Dual Slalom", disciplineId: 7, isPara: false, isActive: true },
  { id: 162, code: "SNO-SG", name: "Snow Bike Super G", disciplineId: 7, isPara: false, isActive: true },
  { id: 163, code: "PIS-EL", name: "Elimination", disciplineId: 8, isPara: false, isActive: true }
];

export function getRaceTypeOptions(disciplineId?: number): RaceTypeOption[] {
  const options: RaceTypeOption[] = [
    { label: 'All', value: null }
  ];

  const filteredTypes = disciplineId 
    ? raceTypes.filter(type => type.disciplineId === disciplineId && type.isActive)
    : raceTypes.filter(type => type.isActive);

  return [
    ...options,
    ...filteredTypes.map(type => ({
      label: type.name,
      value: type.code
    }))
  ];
} 